### ISSUE TITLE
Hi, I'm having trouble starting the bot.

### ISSUE THREAD

**Issue by DanyKrav** [TheCactusMonkey/MinecraftServer-DiscordBot#2]
Hi, I'm having trouble starting the bot, I have configured everything, but when I start it it tells me this: internal / modules / cjs / loader.js: 883   throw err;   ^  Require stack:     at Function.Module._resolveFilename (internal / modules / cjs / loader.js: 880: 15)     at Function.Module._load (internal / modules / cjs / loader.js: 725: 27)     at Module.require (internal / modules / cjs / loader.js: 952: 19)     at require (internal / modules / cjs / helpers.js: 88: 18)     at Object. <anonymous> (C: \ Users \ user \ Desktop \ MinecraftServer-DiscordBot-2.1.1 \ bot.js: 1: 17)     at Module._compile (internal / modules / cjs / loader.js: 1063: 30)     at Object.Module._extensions..js (internal / modules / cjs / loader.js: 1092: 10)     at Module.load (internal / modules / cjs / loader.js: 928: 32)     at Function.Module._load (internal / modules / cjs / loader.js: 769: 14)     at Function.executeUserEntryPoint [as runMain] (internal / modules / run_main.js: 72: 12) {   code: 'MODULE_NOT_FOUND',   requireStack: [     'C: \\ Users \\ user \\ Desktop \\ MinecraftServer-DiscordBot-2.1.1 \\ bot.js'

**Comment by Cactooz** [comment]
Hello,
It seems like you are missing some libraries/have outdated libraries. Have you installed/updated all the needed libraries?
I've also updated the bot with updated libraries and better code the past few days. Try a newer release and see if the problem still exists.

**Comment by Cactooz** [comment]
I just released v3.0.0 of the bot now, which is fully up to date and easier to configure. You can download the new version [here](https://github.com/Cactooz/MinecraftServer-DiscordBot/releases/tag/v3.0.0).

**Comment by Cactooz** [comment]
Closing this issue for now because of inactivity.
I can reopen it if you still have the issue but first try the new version 3.
